apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-grafana-test
  labels:
    app: demo-grafana
spec:
  selector:
    matchLabels:
      app: demo-grafana
  replicas: 1
  template:
    metadata:
      name: demo-grafana-test
      labels:
        app: demo-grafana
    spec:
      containers:
        - name: nginx-pod
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: demo-grafana-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: demo-grafana-lb
  selector:
    app: demo-grafana