name: "01_S3Bucket"
on:
  workflow_dispatch:

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/FeatureBranch1'
    uses: RekhuGopal/gitreusableflows/.github/workflows/aws_tf_plan.yml@FeatureBranch1
    with:
      path: S3Bucket
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Deploy_Dev:
    needs: Plan_Dev
    uses: RekhuGopal/gitreusableflows/.github/workflows/aws_tf_appy.yml@FeatureBranch1
    with:
      path: S3Bucket
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Plan_Uat:
    if: github.ref == 'refs/heads/main'
    uses: RekhuGopal/gitreusableflows/.github/workflows/aws_tf_plan.yml@main
    with:
      path: S3Bucket
      tf_vars_file: uat.tfvars
      gh_environment: uat
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Deploy_Uat:
    needs: Plan_Uat
    uses: RekhuGopal/gitreusableflows/.github/workflows/aws_tf_appy.yml@main
    with:
      path: S3Bucket
      tf_vars_file: uat.tfvars
      gh_environment: uat
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}